// Zigzag Runner - Game Data
const THEMES_DATA = [
    {
        id: 'classic',
        nameKey: 'theme.classic',
        name: 'Classic',
        emoji: '🟦',
        tileColor: '#4a90d9',
        tileHighlight: '#5ba3ec',
        tileShadow: '#3a7bc8',
        bgGradient: ['#0f0c29', '#1a1a3e'],
        ballColor: '#ff6348',
        coinColor: '#ffd700',
        unlockCondition: 'default',
        descKey: 'theme.classic.desc',
        description: 'Default theme',
        particles: { type: 'star', count: 30, speed: 0.5, color: '#ffffff', sizeMin: 1, sizeMax: 3 }
    },
    {
        id: 'neon',
        nameKey: 'theme.neon',
        name: 'Neon',
        emoji: '💜',
        tileColor: '#9b59b6',
        tileHighlight: '#af6ec7',
        tileShadow: '#8e44ad',
        bgGradient: ['#0a0012', '#1a0030'],
        ballColor: '#00ff88',
        coinColor: '#ff00ff',
        unlockCondition: 'score',
        unlockValue: 500,
        descKey: 'theme.neon.desc',
        description: 'Unlock at 500 points',
        particles: { type: 'spark', count: 25, speed: 0.6, colors: ['#ff00ff', '#00ffff'], sizeMin: 1.5, sizeMax: 3.5 }
    },
    {
        id: 'sunset',
        nameKey: 'theme.sunset',
        name: 'Sunset',
        emoji: '🌅',
        tileColor: '#e74c3c',
        tileHighlight: '#f06050',
        tileShadow: '#c0392b',
        bgGradient: ['#2c1810', '#4a2020'],
        ballColor: '#f1c40f',
        coinColor: '#e67e22',
        unlockCondition: 'score',
        unlockValue: 1500,
        descKey: 'theme.sunset.desc',
        description: 'Unlock at 1500 points',
        particles: { type: 'ember', count: 20, speed: 0.4, color: '#ff8c00', sizeMin: 2, sizeMax: 4 }
    },
    {
        id: 'arctic',
        nameKey: 'theme.arctic',
        name: 'Arctic',
        emoji: '❄️',
        tileColor: '#1abc9c',
        tileHighlight: '#2ee0b8',
        tileShadow: '#16a085',
        bgGradient: ['#0a1628', '#122240'],
        ballColor: '#ecf0f1',
        coinColor: '#00d2ff',
        unlockCondition: 'score',
        unlockValue: 3000,
        descKey: 'theme.arctic.desc',
        description: 'Unlock at 3000 points',
        particles: { type: 'snowflake', count: 35, speed: 0.3, color: '#a8d8ff', sizeMin: 1, sizeMax: 2.5 }
    },
    {
        id: 'gold',
        nameKey: 'theme.gold',
        name: 'Gold',
        emoji: '👑',
        tileColor: '#d4a017',
        tileHighlight: '#e8b830',
        tileShadow: '#b8860b',
        bgGradient: ['#1a1400', '#2d2200'],
        ballColor: '#ffffff',
        coinColor: '#ffeaa7',
        unlockCondition: 'score',
        unlockValue: 5000,
        descKey: 'theme.gold.desc',
        description: 'Unlock at 5000 points',
        particles: { type: 'sparkle', count: 25, speed: 0.5, color: '#ffd700', sizeMin: 1.5, sizeMax: 3 }
    }
];

const SKINS_DATA = [
    { id: 'default', nameKey: 'skin.default', name: 'Default Ball', emoji: '🔴', color: null, unlockCondition: 'default' },
    { id: 'blue', nameKey: 'skin.blue', name: 'Blue Ball', emoji: '🔵', color: '#3498db', unlockCondition: 'score', unlockValue: 300 },
    { id: 'green', nameKey: 'skin.green', name: 'Green Ball', emoji: '🟢', color: '#2ecc71', unlockCondition: 'score', unlockValue: 800 },
    { id: 'purple', nameKey: 'skin.purple', name: 'Purple Ball', emoji: '🟣', color: '#9b59b6', unlockCondition: 'score', unlockValue: 1200 },
    { id: 'star', nameKey: 'skin.star', name: 'Star Ball', emoji: '⭐', color: '#f1c40f', unlockCondition: 'score', unlockValue: 2000 },
    { id: 'diamond', nameKey: 'skin.diamond', name: 'Diamond Ball', emoji: '💎', color: '#00d2ff', unlockCondition: 'score', unlockValue: 3500 },
    { id: 'fire', nameKey: 'skin.fire', name: 'Fire Ball', emoji: '🔥', color: '#ff4500', unlockCondition: 'score', unlockValue: 5000 },
    { id: 'rainbow', nameKey: 'skin.rainbow', name: 'Rainbow Ball', emoji: '🌈', color: 'rainbow', unlockCondition: 'score', unlockValue: 8000 }
];

const TITLES_DATA = [
    { score: 0, nameKey: 'title.0', name: 'Baby Steps', emoji: '👶' },
    { score: 50, nameKey: 'title.50', name: 'First Steps', emoji: '🐣' },
    { score: 100, nameKey: 'title.100', name: 'Road Traveler', emoji: '🚶' },
    { score: 200, nameKey: 'title.200', name: 'Turn Apprentice', emoji: '🔄' },
    { score: 350, nameKey: 'title.350', name: 'Agile Runner', emoji: '🏃' },
    { score: 500, nameKey: 'title.500', name: 'Zigzag Explorer', emoji: '🧭' },
    { score: 750, nameKey: 'title.750', name: 'Coin Collector', emoji: '💰' },
    { score: 1000, nameKey: 'title.1000', name: 'Skilled Runner', emoji: '⚡' },
    { score: 1500, nameKey: 'title.1500', name: 'Zigzag Master', emoji: '🎯' },
    { score: 2000, nameKey: 'title.2000', name: 'Turn Expert', emoji: '🌀' },
    { score: 2500, nameKey: 'title.2500', name: 'Infinite Sprinter', emoji: '🏎️' },
    { score: 3000, nameKey: 'title.3000', name: 'Road Ruler', emoji: '👑' },
    { score: 4000, nameKey: 'title.4000', name: 'Legendary Runner', emoji: '🌟' },
    { score: 5000, nameKey: 'title.5000', name: 'Zigzag Hero', emoji: '🦸' },
    { score: 6500, nameKey: 'title.6500', name: 'Transcender', emoji: '🔮' },
    { score: 8000, nameKey: 'title.8000', name: 'Dimensional Walker', emoji: '🌌' },
    { score: 10000, nameKey: 'title.10000', name: 'Spacetime Runner', emoji: '⏳' },
    { score: 15000, nameKey: 'title.15000', name: 'Immortal Stride', emoji: '♾️' },
    { score: 20000, nameKey: 'title.20000', name: 'Edge of Universe', emoji: '🪐' },
    { score: 30000, nameKey: 'title.30000', name: 'God of Zigzag', emoji: '👼' }
];
